### ISSUE TITLE
Import issue on a non-GPU device with cupy installed

### ISSUE THREAD

**Issue by M0hsend** [abTEM/abTEM#120]
Hi abTEM developers,
We recently upgraded to your released version and were getting an `ImportError` regarding cupy. Looking [here](https://github.com/abTEM/abTEM/blob/58633ef63cbf06aa7c9fd52e39a9eedb671bdf34/abtem/core/fft.py#L24) it seems like you need to also catch a case with cupy installed but without GPU. So something like:
`try:
    import cupy as cp
except (ModuleNotFoundError, ImportError):
    cp = None`
Thanks to Tim @ptim0626 for pointing this out!

**Comment by jacobjma** [comment]
I am not sure that abTEM should catch this. I have not tried to install CuPy without a GPU, but I thought that CuPy would catch it and give a reasonable error message.

The suggested change would mean that abTEM defaults to CPU silently. I think users requesting GPU calculations without a GPU should get an error. 

We can make abTEM catch this error and raise a new error telling the user to switch their config to CPU or make sure CuPy works properly.

**Comment by TomaSusi** [comment]
I'm not entirely convinced either. 

@M0hsend @ptim0626, in which circumstances does this arise? If you are setting `device='gpu'` but you don't have CuPy installed, that should throw an error. Otherwise I'm not sure how you would encounter this?

**Comment by ptim0626** [comment]
Hi,
 
I guess the issue is `abtem` can't be imported at all if CuPy throws an error. So I can't `abtem.config.set({"device": "cpu"})` or setting the device to cpu with the instruction [here](https://abtem.github.io/doc/reference/config.html), because `import abtem` or  `from abtem.core import config` would give the `ImportError` from CuPy.

This happens, for example, in a shared environment in HPC systems, where CuPy is present in the Python environment, however the user might not request a GPU, so the CUDA libraries can't be found by CuPy. The current way assumes if you have the package `cupy` installed (not raising `ModuleNotFoundError`), it must be able to find the CUDA libraries, but this is not the case in the above situation.

Looking at the way how it handles the import of `pyfftw`, it seems if the same is done with `cupy`, it can handle the above situation.
https://github.com/abTEM/abTEM/blob/58633ef63cbf06aa7c9fd52e39a9eedb671bdf34/abtem/core/fft.py#L3-L6

**Comment by TomaSusi** [comment]
Ah okay, thank you for that context, that does make sense.

**Comment by ptim0626** [comment]
Yes if the user do not install CuPy, it is caught by the `ModuleNotFoundError` so it should be fine in such case. The thing that should be guarded against is if the user installs CuPy but running `abtem` without a GPU, such as the situation above or for whatever reasons (there is nothing we can stop them in doing this).

**Comment by jacobjma** [comment]
Thank you for the clarification. 

I implemented the suggestion, adding a warning if the user specifically requests GPU calculations. It is live in the development version. I have not tested it with a non-working CuPy, so let me know if there are still problems.
```
try:
    import cupy as cp
except ModuleNotFoundError:
    cp = None
except ImportError:
    if config.get("device") == "gpu":
        warnings.warn(
            "The CuPy library could not be imported. Please check your installation, or change your configuration to "
            "use CPU."
        )
    cp = None
```

**Comment by TomaSusi** [comment]
Great to hear. Yes, the abTEM default is CPU, this is the correct choice for the vast majority of users. GPU has to be explicitly selected.
