### ISSUE TITLE
`SegmentedDetector.show()` throws errors if called with default arguments

### ISSUE THREAD

**Issue by realitychemist** [abTEM/abTEM#130]
Minimal example that reproduces the issue (with `waves=None`, which is the default value of `waves` when calling `show`):
```py
import abtem
detector = abtem.detectors.SegmentedDetector(1, 4, 9, 36)
detector.show(waves=None)  # or just detector.show()
```
Produces an `AttributeError`:
> Traceback (most recent call last):
>   ...
>   File "C:\Users\\...\abtem\detectors.py", line 572, in show
>     segmented_regions = self.get_detector_regions(waves).to_diffraction_patterns(
>   File "C:\Users\\...\abtem\detectors.py", line 521, in get_detector_regions
>     metadata = copy(waves.metadata)
> AttributeError: 'NoneType' object has no attribute 'metadata'

(Relevant line in the repo: https://github.com/abTEM/abTEM/blob/701177b74344970c71da23dbf5f536d2e6aa8a47/abtem/detectors.py#L521C11-L521C11)

This doesn't look like too bad of a bug, however I believe that fixing it the simple way (with a try/except or similar) will result in raising the following error in the default state:

---
Second case (with `waves` set to an instance object derived from `BaseWaves`, but presumably would also happen if `waves=None` and the metadata copy error didn't happen first):
```py
import abtem
detector = abtem.detectors.SegmentedDetector(1, 4, 9, 36)
w = abtem.waves.PlaneWave(energy=200E3)
detector.show(waves=w)
```
Produces a `TypeError`:
> Traceback (most recent call last):
>   ...
>   File "C:\Users\\...\abtem\detectors.py", line 572, in show
>     segmented_regions = self.get_detector_regions(waves).to_diffraction_patterns(
>   File "C:\Users\\...\abtem\measurements.py", line 3135, in to_diffraction_patterns
>     (1 + margin[0]) * self.outer_angle / gpts[0] * 2,
> TypeError: 'NoneType' object is not subscriptable

This is clearly because `gpts` was not set, and setting it resolves this issue.  Likewise setting both `extent` and `sampling`, using `w.grid.match(potential)`, etc... anything that sets `gpts` will resolve this issue.  (Note that `energy` also needs to be set or an essentially similar error results.)

Because of the way `show` uses the `to_diffraction_patterns` method it definitely needs `gpts` to be set.  However (as far as I could see) this isn't documented anywhere, and the signature of `show` having `None` as the default -- `show(self, waves: BaseWave = None)` -- implies that it _isn't_ necessary. I'm not sure if it would be a better option to change the signature and documentation of `show` to make it clear that `waves` is mandatory (and that the wave's `gpts` need to be set), or to change the implementation of `show` to make it so that `waves` is actually optional.

**Comment by TomaSusi** [comment]
Thanks for reporting this, I definitely don't think the code should produce an error here. @jacobjma I'm surprised this happens, maybe an unintended consequence of some more recent functionality..?

**Comment by jacobjma** [comment]
@realitychemist Thank you for the report. I addressed most of it with [this commit](https://github.com/abTEM/abTEM/commit/5455949b7eda3e206572da24c9784ac48addf5fd). 
@TomaSusi Yes, there were some changes; I wanted to leverage abTEM's visualization module instead of making custom plots for the detectors. 

The `gpts`, `sampling`, and `energy`, should come from somewhere, to have a visualization that matches the `Waves`, however, that is probably not necessary in most cases.

It is now implemented with a default value of `gpts=1024` and a `sampling` such that the outer angle of the detector region is covered plus a margin. You can provide either `waves` or `gpts` and `sampling.` 

The `energy` (or `Waves` with an `energy`) _currently_ still has to be specified due to some inflexibility in how the visualization module works. This should not be necessary once I merge some improvements, that currently exist in another branch. The thread can be left up until then.

**Comment by jacobjma** [comment]
Fixed in main branch now.
