### ISSUE TITLE
How can I use abtem to read an experimental 4DSTEM data?

### ISSUE THREAD

**Issue by PhysXu** [abTEM/abTEM#139]
Hi, I want to try the ePIE in abtem to treat my experimental 4DSTEM data.
However, I have a problem to read my data via abtem.
From the the demo: https://github.com/abTEM/abTEM/blob/main/articles/2021_ORE_abTEM/MoS2_ptycho.ipynb
it looks like I can load my data via the "Measurement.read", but I met an error when run these codes:
<img width="586" alt="image" src="https://github.com/abTEM/abTEM/assets/35793078/0bc0a210-b3a5-437e-9299-ceb0f2b204f1">

I install batem by pip, and the version is 1.0.4

BTW, the format of my data is *dm3.

Any response will be appreciated very much!

**Comment by TomaSusi** [comment]
Hi! The problem you are encountering is because you are trying to use a notebook from the old version of the code with the latest abTEM, whose up-to-date documentation can be found at:
https://abtem.github.io/doc/user_guide/tutorials/epie.html

However, we do not recommend using *ab*TEM for ePIE reconstructions of experimental data, as real data has any number of imperfections that we are not set up to handle well.

py4DSTEM has a number of ptychographic algorithms that are built for experimental data, and we recommend you look into those:
https://github.com/py4dstem/py4DSTEM_tutorials/tree/main/notebooks

**Comment by PhysXu** [comment]
> Hi! The problem you are encountering is because you are trying to use a notebook from the old version of the code with the latest _ab_TEM, whose up-to-date documentation can be found at: https://abtem.github.io/doc/user_guide/tutorials/epie.html
> 
> However, we do not recommend using _ab_TEM for ePIE reconstructions of experimental data, as real data has any number of imperfections that we are not set up to handle well.
> 
> py4DSTEM has a number of ptychographic algorithms that are built for experimental data, and we recommend you look into those: https://github.com/py4dstem/py4DSTEM_tutorials/tree/main/notebooks

Thanks for your reply. I will try py4DSTEM following your suggestions.
