### ISSUE TITLE
Creating synthetic atom with weighted average of atomic potential 

### ISSUE THREAD

**Issue by GabrielVazquezLizardi** [abTEM/abTEM#158]
Hello. I am looking to generate CBED simulations where I create a synthetic atom which atomic potential is the weighted average of two different atoms. I have look at both ASE and abTEM documentation but have not found an answer to this. Is this possible?

Currently I have created a random distribution of these species (using ASE) to generate the CBED patterns, however, I can only take a single CBED pattern. If the above was not possible can multiple CBED patterns be simulated and the average of this stored as a single .zarr file. Below are the lines of code I used to run the CBED simulation.

```
potential = abtem.Potential(structure, 
            slice_thickness = 2
            sampling = 0.2,
            parametrization = 'lobato', 
            projection = 'infinite', 
            exit_planes = 10
)

probe = abtem.Probe(energy=100000, semiangle_cutoff = 5, sampling= 0.2)

probe_exit_wave = probe.multislice(potential)
probe_exit_wave.to_zarr(f'{storage_output}/CBED_{key}.zarr', compute=False, overwrite=True)
probe_exit_wave.compute()
```

Thanks for the help,
Gabriel

**Comment by TomaSusi** [comment]
Hi Gabriel!

Hmm... why do you want to do that, exactly? Our approach in abTEM has been that we want exact atomic models for the specific systems we simulate, and if there is for example a mixture of occupancies, that needs to be included explicitly on the level of the atomic model, with results averaged in the end (instead of using something ultimately unphysical to emulate the real situation).

But to answer you more directly: ultimately the potential is an array, so if you build and compute each atom separately in the same cell, you can take weighted average of their arrays as your potential array. We don't support this directly but you can always access the arrays in our objects if you need to hack under the hood.

I'm not sure what you mean by "I can only take a single CBED pattern"? Without defining any scan with probe, your simulation will only include a single probe position. So if you have different atoms in different parts of the same simulation cell, you could define a custom scan with coordinates matching those atoms, and then save the resulting scanned measurement in single Zarr file as normal.

**Comment by GabrielVazquezLizardi** [comment]
Hello Toma. Thank you for your quick response! The primary reason is that I want to create an average CBED pattern of Pb(Zr0.48Ti0.52)O3 where the Ti and Zr are mix across sample. The two ways I thought of doing this was to simulated various CBED patterns across the model, and taking the average of them; while the second option was to create the model and then replace the Zr and Ti with the synthetic atom. 

I will try and see if I can modify the potential this way. However, I think creating the custom scan will be faster to implement for me. I appreciate your help.

**Comment by TomaSusi** [comment]
That's exactly the type of case where our philosophy is: create explicit atomic models with the desired variation, simulate each physical structure separately, and average the results.
