### ISSUE TITLE
PartitionedSMatrix has no ._generate_probes() method

### ISSUE THREAD

**Issue by hisigns** [abTEM/abTEM#84]
I am running a simulation that is too big to fit in memory so I used the num_partitions=2 flag while creating my SMatrix array. When I try and use the S.scan method I get something similar to the error in the title: PartitionedSMatrix has no ._generate_probes() method. 

I am not sure if I am setting up the PartitionedSMatrix object and scan correctly - Here are my current inputs:
![Screenshot from 2022-06-24 22-47-09](https://user-images.githubusercontent.com/56736812/175760695-cef564b4-1200-49e8-b77c-87dd28674732.png)
![Screenshot from 2022-06-24 22-48-04](https://user-images.githubusercontent.com/56736812/175760700-e1251a18-8bf2-4be1-a898-58595dcbbee6.png)

I looked into where the error was showing up and added some print statements to see what kind of object,  "S" ,( an SMatrix or PartitionedSMatrix) was being referenced in each step. For the 3 print statements shown below all "S"  are PartitionedSMatrix objects. 

![Screenshot from 2022-06-24 22-36-44](https://user-images.githubusercontent.com/56736812/175759935-dc789801-9e40-4fa7-8efc-219a9663634f.png)

But I can't find a _generate_probes() method in the PartitionedSMatrix class.

**Comment by jacobjma** [comment]
I am afraid I never fully finished the implementation of the partitioned PRISM algorithm in the current main branch. I have continued working on the implementation in the `abtem-dask` branch. However, because no one (until now), has expressed interest in using the algorithm, it has not been prioritized.

I will update this issue when it is available. It is pretty close to finished, so maybe I have time to finish it this week.
