### ISSUE TITLE
Request - allow full size output for pixelated detector 

### ISSUE THREAD

**Issue by cophus** [abTEM/abTEM#88]
When using PRISM in abTEM + complex output, it seems like the subpixel position of the probe is not correct.  This result is inconsistent however so I have a request:
in `class PixelatedDetector(AbstractDetector):`

Specifically this option:
```
max_angle : str or float or None
        The diffraction patterns will be detected up to this angle. If set to a string it must be 'limit' or 'valid'

```
Could we add 'full' and output the `gpts`-sized output?  i.e. still apply the 2/3s anti-aliasing aperture, but have the output be the same size as the potentials.  This will allow me to carefully test the subpixel probe positions in both multislice and PRISM (when using complex output).  I wasn't sure where in the code the cropping actually happens.

**Comment by jacobjma** [comment]
This should be possible by setting `max_angle=None`, but this definitely quite badly documented. Having the "full" keyword is a good idea.
For debugging you might want to use the `WavefunctionDetector`, which just saves the wave function.

Is the actual position incorrect or is the cropping to that position incorrect? Are the gpts divisible by the interpolation factor?

**Comment by jacobjma** [comment]
Ahh, I think I see what the problem is. The SMatrix is downsampled after running multislice on each plane wave to save memory. I thought there already was an option to disable this, but apparently only in the dask branch.

I just added a `downsample` argument to `SMatrix` which will let you disable downsampling.  

To get full diffraction patterns, set `max_angle=None` and set `downsample=False`. For example, the following code
```
potential = Potential(atoms, gpts=(300, 600))
detector = PixelatedDetector(max_angle=None)
S = SMatrix(energy=150e3, expansion_cutoff=20, semiangle_cutoff=20, interpolation=(1,2), downsample=False)
measurement = S.scan(scan, detector, potential)
```
will return measurement a of shape `(10,20,300,300)`.

The below will return the downsampled diffraction patterns as before. For example, the following
```python
potential = Potential(atoms, gpts=(300, 600))
S = SMatrix(energy=150e3, expansion_cutoff=20, semiangle_cutoff=20, interpolation=(1,2), downsample=True)
detector = PixelatedDetector()
measurement = S.scan(scan, detector, potential)
```
will return measurement a of shape `(10,20,200,200)`.
